# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "hugo-theme-arvinsim.com"
license = "MIT"
licenselink = "https://github.com/arvinsim/hugo-theme-arvinsim.com/blob/master/LICENSE.md"
description = "hugo-theme-arvinsim.com is a simple theme created for my personal blog."
homepage = "https://github.com/arvinsim/hugo-theme-arvinsim.com"
tags = ["dark", "minimalist", "green"]
features = ["blog"]
min_version = 0.25.1

[author]
  name = "Arthur Vincent Simon"
  homepage = "http://arthurvincentsimon.com" 